### ISSUE TITLE
Bounce with Redis

### ISSUE THREAD

**Issue by IngwiePhoenix** [znarf/bouncer#8]
Hey.

I would like to suggest that Bouncer becomes Redis-aware. I wanted to add Bouncer to my project, but it is heavily Redis based and therefore installing Memcached would be a bit of an overhead.

Since Redis is easily usable in PHP, would it be possible to make Bouncer aware of Redis?

**Comment by znarf** [comment]
Bouncer is already Redis aware. And it's even recommended to use it as a backend. You can use it like that:

```
Bouncer::run(array('backend' => 'phpredis', 'servers' => array('127.0.0.1'));
```
